import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import type { BatchAuditResult } from './types';

/**
 * Generate PDF report from audit results
 */
export function generatePDFReport(result: BatchAuditResult): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Schema Audit Report', pageWidth / 2, 20, { align: 'center' });

  // Date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const dateStr = new Date().toLocaleString();
  doc.text(`Generated: ${dateStr}`, pageWidth / 2, 28, { align: 'center' });

  // Summary Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 14, 40);

  const summaryData = [
    ['Total URLs', result.summary.totalUrls.toString()],
    ['Successful', result.summary.successfulUrls.toString()],
    ['Failed', result.summary.failedUrls.toString()],
    ['Average Score', `${result.summary.avgScore}/100`],
    ['Total Errors', result.summary.totalErrors.toString()],
    ['Total Warnings', result.summary.totalWarnings.toString()],
    [
      'Rich Results Eligible',
      `${result.summary.eligibleForRichResults}/${result.summary.totalUrls}`,
    ],
    [
      'Duration',
      `${Math.round(result.summary.duration / 1000)}s`,
    ],
  ];

  autoTable(doc, {
    startY: 45,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229] }, // Indigo
  });

  // Results Table
  doc.addPage();
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Detailed Results', 14, 20);

  const resultsData = result.results.map((item) => [
    item.url.length > 60 ? item.url.substring(0, 57) + '...' : item.url,
    item.validation ? item.validation.overallScore.toString() : 'N/A',
    item.validation ? item.validation.summary.totalErrors.toString() : '-',
    item.validation ? item.validation.summary.totalWarnings.toString() : '-',
    item.validation && item.validation.summary.richResultsEligible ? 'Yes' : 'No',
    item.error ? 'Failed' : 'Success',
  ]);

  autoTable(doc, {
    startY: 25,
    head: [['URL', 'Score', 'Errors', 'Warnings', 'Eligible', 'Status']],
    body: resultsData,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229] },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: 20 },
      2: { cellWidth: 20 },
      3: { cellWidth: 25 },
      4: { cellWidth: 20 },
      5: { cellWidth: 25 },
    },
    styles: { fontSize: 8, cellPadding: 2 },
  });

  // Footer on each page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(128);
    doc.text(
      'Generated by Schema Validator',
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  // Save PDF
  const filename = `schema-audit-${Date.now()}.pdf`;
  doc.save(filename);
}

/**
 * Generate Excel report from audit results
 */
export function generateExcelReport(result: BatchAuditResult): void {
  const workbook = XLSX.utils.book_new();

  // Summary Sheet
  const summaryData = [
    ['Schema Audit Report'],
    ['Generated', new Date().toLocaleString()],
    [],
    ['Metric', 'Value'],
    ['Total URLs', result.summary.totalUrls],
    ['Successful', result.summary.successfulUrls],
    ['Failed', result.summary.failedUrls],
    ['Average Score', result.summary.avgScore],
    ['Total Errors', result.summary.totalErrors],
    ['Total Warnings', result.summary.totalWarnings],
    ['Rich Results Eligible', result.summary.eligibleForRichResults],
    ['Duration (seconds)', Math.round(result.summary.duration / 1000)],
  ];

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);

  // Style the summary sheet
  summarySheet['!cols'] = [{ wch: 25 }, { wch: 20 }];

  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

  // Details Sheet
  const detailsData = [
    [
      'URL',
      'SEO Score',
      'Errors',
      'Warnings',
      'Passed Checks',
      'Eligible for Rich Results',
      'Status',
      'Duration (ms)',
    ],
  ];

  for (const item of result.results) {
    detailsData.push([
      item.url,
      item.validation?.overallScore.toString() || 'N/A',
      (item.validation?.summary.totalErrors || 0).toString(),
      (item.validation?.summary.totalWarnings || 0).toString(),
      (item.validation?.summary.totalPassed || 0).toString(),
      item.validation?.summary.richResultsEligible ? 'Yes' : 'No',
      item.error ? 'Failed' : 'Success',
      item.duration.toString(),
    ]);
  }

  const detailsSheet = XLSX.utils.aoa_to_sheet(detailsData);

  // Set column widths
  detailsSheet['!cols'] = [
    { wch: 50 }, // URL
    { wch: 12 }, // Score
    { wch: 10 }, // Errors
    { wch: 12 }, // Warnings
    { wch: 15 }, // Passed
    { wch: 22 }, // Eligible
    { wch: 10 }, // Status
    { wch: 15 }, // Duration
  ];

  XLSX.utils.book_append_sheet(workbook, detailsSheet, 'Detailed Results');

  // Errors Sheet (if any errors exist)
  const errorsData: (string | number)[][] = [['URL', 'Error Message', 'Fix']];

  for (const item of result.results) {
    if (item.validation && item.validation.schemas.length > 0) {
      for (const schema of item.validation.schemas) {
        for (const error of schema.errors) {
          errorsData.push([item.url, error.message, error.fix || 'N/A']);
        }
      }
    }
  }

  if (errorsData.length > 1) {
    const errorsSheet = XLSX.utils.aoa_to_sheet(errorsData);
    errorsSheet['!cols'] = [{ wch: 50 }, { wch: 40 }, { wch: 50 }];
    XLSX.utils.book_append_sheet(workbook, errorsSheet, 'Errors');
  }

  // Warnings Sheet (if any warnings exist)
  const warningsData: (string | number)[][] = [
    ['URL', 'Warning Message', 'Fix'],
  ];

  for (const item of result.results) {
    if (item.validation && item.validation.schemas.length > 0) {
      for (const schema of item.validation.schemas) {
        for (const warning of schema.warnings) {
          warningsData.push([item.url, warning.message, warning.fix || 'N/A']);
        }
      }
    }
  }

  if (warningsData.length > 1) {
    const warningsSheet = XLSX.utils.aoa_to_sheet(warningsData);
    warningsSheet['!cols'] = [{ wch: 50 }, { wch: 40 }, { wch: 50 }];
    XLSX.utils.book_append_sheet(workbook, warningsSheet, 'Warnings');
  }

  // Save Excel file
  const filename = `schema-audit-${Date.now()}.xlsx`;
  XLSX.writeFile(workbook, filename);
}

/**
 * Generate JSON export
 */
export function generateJSONReport(result: BatchAuditResult): void {
  const json = JSON.stringify(result, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `schema-audit-${Date.now()}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
