/**
 * Event Schema Validation Rules
 * https://schema.org/Event
 * https://developers.google.com/search/docs/appearance/structured-data/event
 */

import type { ValidationRule } from '../types';

export const eventRules: ValidationRule[] = [
  {
    property: '@context',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: '@context must be "https://schema.org"',
    fix: 'Set "@context": "https://schema.org"',
    documentation: 'https://schema.org/Event',
  },
  {
    property: '@type',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: '@type must be "Event"',
    fix: 'Set "@type": "Event"',
    documentation: 'https://schema.org/Event',
  },
  {
    property: 'name',
    required: true,
    type: 'string',
    minLength: 5,
    seoImpact: 'high',
    errorMessage: 'name (event title) is required',
    fix: 'Add "name": "Event Name"',
    documentation: 'https://schema.org/name',
  },
  {
    property: 'startDate',
    required: true,
    type: 'string',
    format: 'iso8601-datetime',
    seoImpact: 'high',
    errorMessage: 'startDate is required in ISO 8601 format',
    fix: 'Add "startDate": "2024-07-21T19:00:00-05:00"',
    documentation: 'https://schema.org/startDate',
  },
  {
    property: 'location',
    required: true,
    type: 'object',
    seoImpact: 'high',
    errorMessage: 'location is required (Place or VirtualLocation)',
    fix: 'Add "location": {"@type": "Place", "name": "Venue Name", "address": "..."}',
    documentation: 'https://developers.google.com/search/docs/appearance/structured-data/event',
  },
  {
    property: 'location.@type',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: 'location must have @type "Place" or "VirtualLocation"',
    fix: 'Set "@type": "Place" or "@type": "VirtualLocation"',
    documentation: 'https://schema.org/Place',
  },
  {
    property: 'location.name',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: 'location.name is required',
    fix: 'Add "name": "Venue Name"',
    documentation: 'https://schema.org/Place',
  },
  {
    property: 'location.address',
    required: false,
    type: ['string', 'object'],
    seoImpact: 'medium',
    errorMessage: 'location.address is recommended for physical events',
    fix: 'Add "address": {"@type": "PostalAddress", "streetAddress": "...", "addressLocality": "..."}',
    documentation: 'https://schema.org/address',
  },
  {
    property: 'endDate',
    required: false,
    type: 'string',
    format: 'iso8601-datetime',
    seoImpact: 'medium',
    errorMessage: 'endDate is recommended',
    fix: 'Add "endDate": "2024-07-21T23:00:00-05:00"',
    documentation: 'https://schema.org/endDate',
  },
  {
    property: 'description',
    required: false,
    type: 'string',
    minLength: 50,
    seoImpact: 'medium',
    errorMessage: 'description is recommended',
    fix: 'Add "description": "Event description"',
    documentation: 'https://schema.org/description',
  },
  {
    property: 'image',
    required: false,
    type: ['string', 'array'],
    googleRequirement: {
      minWidth: 696,
      minHeight: 400,
    },
    seoImpact: 'medium',
    errorMessage: 'image is recommended for enhanced display (should be at least 696x400 pixels)',
    fix: 'Add "image": "https://example.com/event-image.jpg"',
    documentation: 'https://developers.google.com/search/docs/appearance/structured-data/event',
  },
  {
    property: 'organizer',
    required: false,
    type: 'object',
    seoImpact: 'low',
    errorMessage: 'organizer is recommended',
    fix: 'Add "organizer": {"@type": "Organization", "name": "Organizer Name"}',
    documentation: 'https://schema.org/organizer',
  },
  {
    property: 'performer',
    required: false,
    type: ['object', 'array'],
    seoImpact: 'low',
    errorMessage: 'performer is optional but helpful',
    fix: 'Add "performer": {"@type": "Person", "name": "Performer Name"}',
    documentation: 'https://schema.org/performer',
  },
  {
    property: 'offers',
    required: false,
    type: ['object', 'array'],
    seoImpact: 'medium',
    errorMessage: 'offers information is recommended for ticket sales',
    fix: 'Add "offers": {"@type": "Offer", "url": "...", "price": "30", "priceCurrency": "USD"}',
    documentation: 'https://schema.org/offers',
  },
  {
    property: 'eventStatus',
    required: false,
    type: 'string',
    seoImpact: 'medium',
    errorMessage: 'eventStatus is recommended (especially for COVID-19 updates)',
    fix: 'Add "eventStatus": "https://schema.org/EventScheduled"',
    documentation: 'https://schema.org/eventStatus',
  },
  {
    property: 'eventAttendanceMode',
    required: false,
    type: 'string',
    seoImpact: 'medium',
    errorMessage: 'eventAttendanceMode is recommended (OfflineEventAttendanceMode, OnlineEventAttendanceMode, or MixedEventAttendanceMode)',
    fix: 'Add "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode"',
    documentation: 'https://schema.org/eventAttendanceMode',
  },
];
