/**
 * HowTo Schema Validation Rules
 * https://schema.org/HowTo
 * https://developers.google.com/search/docs/appearance/structured-data/how-to
 */

import type { ValidationRule } from '../types';

export const howToRules: ValidationRule[] = [
  {
    property: '@context',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: '@context must be "https://schema.org"',
    fix: 'Set "@context": "https://schema.org"',
    documentation: 'https://schema.org/HowTo',
  },
  {
    property: '@type',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: '@type must be "HowTo"',
    fix: 'Set "@type": "HowTo"',
    documentation: 'https://schema.org/HowTo',
  },
  {
    property: 'name',
    required: true,
    type: 'string',
    minLength: 10,
    seoImpact: 'high',
    errorMessage: 'name (title) is required',
    fix: 'Add "name": "How to do something"',
    documentation: 'https://schema.org/name',
  },
  {
    property: 'step',
    required: true,
    type: 'array',
    seoImpact: 'high',
    errorMessage: 'step array is required with at least one HowToStep',
    fix: 'Add "step": [{"@type": "HowToStep", "name": "...", "text": "..."}]',
    documentation: 'https://developers.google.com/search/docs/appearance/structured-data/how-to',
  },
  {
    property: 'step[].@type',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: 'Each step must have @type "HowToStep"',
    fix: 'Set "@type": "HowToStep"',
    documentation: 'https://schema.org/HowToStep',
  },
  {
    property: 'step[].name',
    required: false,
    type: 'string',
    seoImpact: 'medium',
    errorMessage: 'Step name is recommended for better display',
    fix: 'Add "name": "Step title" to each step',
    documentation: 'https://schema.org/HowToStep',
  },
  {
    property: 'step[].text',
    required: true,
    type: 'string',
    minLength: 10,
    seoImpact: 'high',
    errorMessage: 'Each step must have text instructions',
    fix: 'Add "text": "Detailed step instructions"',
    documentation: 'https://schema.org/HowToStep',
  },
  {
    property: 'image',
    required: false,
    type: ['string', 'object', 'array'],
    googleRequirement: {
      minWidth: 696,
      minHeight: 400,
    },
    seoImpact: 'medium',
    errorMessage: 'image is recommended for rich results (should be at least 696x400 pixels for optimal display)',
    fix: 'Add "image": "https://example.com/image.jpg"',
    documentation: 'https://developers.google.com/search/docs/appearance/structured-data/how-to',
  },
  {
    property: 'description',
    required: false,
    type: 'string',
    minLength: 50,
    seoImpact: 'medium',
    errorMessage: 'description is recommended',
    fix: 'Add "description": "Brief overview of the how-to"',
    documentation: 'https://schema.org/description',
  },
  {
    property: 'totalTime',
    required: false,
    type: 'string',
    format: 'iso8601-duration',
    seoImpact: 'low',
    errorMessage: 'totalTime should be in ISO 8601 duration format',
    fix: 'Add "totalTime": "PT30M" (for 30 minutes)',
    documentation: 'https://schema.org/totalTime',
  },
  {
    property: 'estimatedCost',
    required: false,
    type: 'object',
    seoImpact: 'low',
    errorMessage: 'estimatedCost is optional but recommended',
    fix: 'Add "estimatedCost": {"@type": "MonetaryAmount", "currency": "USD", "value": "10"}',
    documentation: 'https://schema.org/estimatedCost',
  },
  {
    property: 'supply',
    required: false,
    type: 'array',
    seoImpact: 'low',
    errorMessage: 'supply list is optional but recommended',
    fix: 'Add "supply": [{"@type": "HowToSupply", "name": "Item name"}]',
    documentation: 'https://schema.org/supply',
  },
  {
    property: 'tool',
    required: false,
    type: 'array',
    seoImpact: 'low',
    errorMessage: 'tool list is optional but recommended',
    fix: 'Add "tool": [{"@type": "HowToTool", "name": "Tool name"}]',
    documentation: 'https://schema.org/tool',
  },
];
