/**
 * JobPosting Schema Validation Rules
 * https://schema.org/JobPosting
 * https://developers.google.com/search/docs/appearance/structured-data/job-posting
 */

import type { ValidationRule } from '../types';

export const jobPostingRules: ValidationRule[] = [
  {
    property: '@context',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: '@context must be "https://schema.org"',
    fix: 'Set "@context": "https://schema.org"',
    documentation: 'https://schema.org/JobPosting',
  },
  {
    property: '@type',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: '@type must be "JobPosting"',
    fix: 'Set "@type": "JobPosting"',
    documentation: 'https://schema.org/JobPosting',
  },
  {
    property: 'title',
    required: true,
    type: 'string',
    minLength: 5,
    seoImpact: 'high',
    errorMessage: 'title (job title) is required',
    fix: 'Add "title": "Software Engineer"',
    documentation: 'https://schema.org/title',
  },
  {
    property: 'description',
    required: true,
    type: 'string',
    minLength: 100,
    seoImpact: 'high',
    errorMessage: 'description is required with complete job description',
    fix: 'Add "description": "Detailed job description with responsibilities, qualifications, etc."',
    documentation: 'https://schema.org/description',
  },
  {
    property: 'datePosted',
    required: true,
    type: 'string',
    format: 'iso8601-date',
    seoImpact: 'high',
    errorMessage: 'datePosted is required in ISO 8601 format',
    fix: 'Add "datePosted": "2024-01-15"',
    documentation: 'https://schema.org/datePosted',
  },
  {
    property: 'validThrough',
    required: false,
    type: 'string',
    format: 'iso8601-datetime',
    seoImpact: 'medium',
    errorMessage: 'validThrough is recommended to indicate job posting expiry',
    fix: 'Add "validThrough": "2024-03-15T00:00"',
    documentation: 'https://schema.org/validThrough',
  },
  {
    property: 'hiringOrganization',
    required: true,
    type: 'object',
    seoImpact: 'high',
    errorMessage: 'hiringOrganization is required',
    fix: 'Add "hiringOrganization": {"@type": "Organization", "name": "Company Name"}',
    documentation: 'https://developers.google.com/search/docs/appearance/structured-data/job-posting',
  },
  {
    property: 'hiringOrganization.@type',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: 'hiringOrganization must have @type "Organization"',
    fix: 'Set "@type": "Organization"',
    documentation: 'https://schema.org/Organization',
  },
  {
    property: 'hiringOrganization.name',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: 'hiringOrganization.name is required',
    fix: 'Add "name": "Company Name"',
    documentation: 'https://schema.org/Organization',
  },
  {
    property: 'hiringOrganization.sameAs',
    required: false,
    type: 'string',
    seoImpact: 'low',
    errorMessage: 'hiringOrganization.sameAs (company URL) is recommended',
    fix: 'Add "sameAs": "https://www.company.com"',
    documentation: 'https://schema.org/sameAs',
  },
  {
    property: 'jobLocation',
    required: true,
    type: ['object', 'array'],
    seoImpact: 'high',
    errorMessage: 'jobLocation is required',
    fix: 'Add "jobLocation": {"@type": "Place", "address": {"@type": "PostalAddress", "addressLocality": "City", "addressRegion": "State", "addressCountry": "US"}}',
    documentation: 'https://developers.google.com/search/docs/appearance/structured-data/job-posting',
  },
  {
    property: 'jobLocation.@type',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: 'jobLocation must have @type "Place"',
    fix: 'Set "@type": "Place"',
    documentation: 'https://schema.org/Place',
  },
  {
    property: 'jobLocation.address',
    required: true,
    type: 'object',
    seoImpact: 'high',
    errorMessage: 'jobLocation.address is required',
    fix: 'Add "address": {"@type": "PostalAddress", "addressLocality": "...", "addressRegion": "...", "addressCountry": "..."}',
    documentation: 'https://schema.org/address',
  },
  {
    property: 'baseSalary',
    required: false,
    type: 'object',
    seoImpact: 'medium',
    errorMessage: 'baseSalary is recommended for better visibility',
    fix: 'Add "baseSalary": {"@type": "MonetaryAmount", "currency": "USD", "value": {"@type": "QuantitativeValue", "value": 40000, "unitText": "YEAR"}}',
    documentation: 'https://schema.org/baseSalary',
  },
  {
    property: 'employmentType',
    required: false,
    type: ['string', 'array'],
    seoImpact: 'medium',
    errorMessage: 'employmentType is recommended (FULL_TIME, PART_TIME, CONTRACTOR, TEMPORARY, INTERN, VOLUNTEER, PER_DIEM, OTHER)',
    fix: 'Add "employmentType": "FULL_TIME"',
    documentation: 'https://schema.org/employmentType',
  },
  {
    property: 'jobLocationType',
    required: false,
    type: 'string',
    seoImpact: 'medium',
    errorMessage: 'jobLocationType is recommended for remote jobs (TELECOMMUTE)',
    fix: 'Add "jobLocationType": "TELECOMMUTE" for remote positions',
    documentation: 'https://schema.org/jobLocationType',
  },
  {
    property: 'applicantLocationRequirements',
    required: false,
    type: 'object',
    seoImpact: 'low',
    errorMessage: 'applicantLocationRequirements is optional for geographic restrictions',
    fix: 'Add "applicantLocationRequirements": {"@type": "Country", "name": "US"}',
    documentation: 'https://schema.org/applicantLocationRequirements',
  },
  {
    property: 'workHours',
    required: false,
    type: 'string',
    seoImpact: 'low',
    errorMessage: 'workHours is optional',
    fix: 'Add "workHours": "40 hours per week"',
    documentation: 'https://schema.org/workHours',
  },
  {
    property: 'directApply',
    required: false,
    type: 'boolean',
    seoImpact: 'low',
    errorMessage: 'directApply indicates if users can apply directly',
    fix: 'Add "directApply": true',
    documentation: 'https://developers.google.com/search/docs/appearance/structured-data/job-posting',
  },
];
