/**
 * Recipe Schema Validation Rules
 * https://schema.org/Recipe
 * https://developers.google.com/search/docs/appearance/structured-data/recipe
 */

import type { ValidationRule } from '../types';

export const recipeRules: ValidationRule[] = [
  {
    property: '@context',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: '@context must be "https://schema.org"',
    fix: 'Set "@context": "https://schema.org"',
    documentation: 'https://schema.org/Recipe',
  },
  {
    property: '@type',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: '@type must be "Recipe"',
    fix: 'Set "@type": "Recipe"',
    documentation: 'https://schema.org/Recipe',
  },
  {
    property: 'name',
    required: true,
    type: 'string',
    minLength: 5,
    seoImpact: 'high',
    errorMessage: 'name (recipe title) is required',
    fix: 'Add "name": "Recipe Name"',
    documentation: 'https://schema.org/name',
  },
  {
    property: 'image',
    required: true,
    type: ['string', 'object', 'array'],
    googleRequirement: {
      minWidth: 696,
      minHeight: 400,
    },
    seoImpact: 'high',
    errorMessage: 'image is required for recipe rich results (must be at least 696x400 pixels)',
    fix: 'Add "image": "https://example.com/recipe-image.jpg"',
    documentation: 'https://developers.google.com/search/docs/appearance/structured-data/recipe',
  },
  {
    property: 'author',
    required: false,
    type: ['string', 'object'],
    seoImpact: 'medium',
    errorMessage: 'author is recommended',
    fix: 'Add "author": {"@type": "Person", "name": "Chef Name"} or "author": "Chef Name"',
    documentation: 'https://schema.org/author',
  },
  {
    property: 'datePublished',
    required: false,
    type: 'string',
    format: 'iso8601-date',
    seoImpact: 'low',
    errorMessage: 'datePublished should be in ISO 8601 format',
    fix: 'Add "datePublished": "2024-01-15"',
    documentation: 'https://schema.org/datePublished',
  },
  {
    property: 'description',
    required: false,
    type: 'string',
    minLength: 50,
    seoImpact: 'medium',
    errorMessage: 'description is recommended',
    fix: 'Add "description": "Brief description of the recipe"',
    documentation: 'https://schema.org/description',
  },
  {
    property: 'prepTime',
    required: false,
    type: 'string',
    format: 'iso8601-duration',
    seoImpact: 'medium',
    errorMessage: 'prepTime should be in ISO 8601 duration format',
    fix: 'Add "prepTime": "PT15M" (for 15 minutes)',
    documentation: 'https://schema.org/prepTime',
  },
  {
    property: 'cookTime',
    required: false,
    type: 'string',
    format: 'iso8601-duration',
    seoImpact: 'medium',
    errorMessage: 'cookTime should be in ISO 8601 duration format',
    fix: 'Add "cookTime": "PT30M" (for 30 minutes)',
    documentation: 'https://schema.org/cookTime',
  },
  {
    property: 'totalTime',
    required: false,
    type: 'string',
    format: 'iso8601-duration',
    seoImpact: 'medium',
    errorMessage: 'totalTime should be in ISO 8601 duration format',
    fix: 'Add "totalTime": "PT45M" (for 45 minutes)',
    documentation: 'https://schema.org/totalTime',
  },
  {
    property: 'recipeYield',
    required: false,
    type: 'string',
    seoImpact: 'medium',
    errorMessage: 'recipeYield is recommended',
    fix: 'Add "recipeYield": "4 servings" or "recipeYield": "12 cookies"',
    documentation: 'https://schema.org/recipeYield',
  },
  {
    property: 'recipeCategory',
    required: false,
    type: 'string',
    seoImpact: 'low',
    errorMessage: 'recipeCategory is optional but helpful',
    fix: 'Add "recipeCategory": "Dessert"',
    documentation: 'https://schema.org/recipeCategory',
  },
  {
    property: 'recipeCuisine',
    required: false,
    type: 'string',
    seoImpact: 'low',
    errorMessage: 'recipeCuisine is optional but helpful',
    fix: 'Add "recipeCuisine": "Italian"',
    documentation: 'https://schema.org/recipeCuisine',
  },
  {
    property: 'keywords',
    required: false,
    type: 'string',
    seoImpact: 'low',
    errorMessage: 'keywords are optional but helpful for search',
    fix: 'Add "keywords": "chocolate, cookies, dessert"',
    documentation: 'https://schema.org/keywords',
  },
  {
    property: 'recipeIngredient',
    required: false,
    type: 'array',
    seoImpact: 'high',
    errorMessage: 'recipeIngredient is strongly recommended',
    fix: 'Add "recipeIngredient": ["2 cups flour", "1 cup sugar"]',
    documentation: 'https://schema.org/recipeIngredient',
  },
  {
    property: 'recipeInstructions',
    required: false,
    type: ['string', 'array'],
    seoImpact: 'high',
    errorMessage: 'recipeInstructions are strongly recommended',
    fix: 'Add "recipeInstructions": "Step-by-step instructions" or array of HowToStep objects',
    documentation: 'https://schema.org/recipeInstructions',
  },
  {
    property: 'nutrition',
    required: false,
    type: 'object',
    seoImpact: 'low',
    errorMessage: 'nutrition information is optional but helpful',
    fix: 'Add "nutrition": {"@type": "NutritionInformation", "calories": "270 calories"}',
    documentation: 'https://schema.org/nutrition',
  },
  {
    property: 'aggregateRating',
    required: false,
    type: 'object',
    seoImpact: 'medium',
    errorMessage: 'aggregateRating is recommended for star ratings',
    fix: 'Add "aggregateRating": {"@type": "AggregateRating", "ratingValue": "4.5", "reviewCount": "100"}',
    documentation: 'https://schema.org/aggregateRating',
  },
  {
    property: 'video',
    required: false,
    type: 'object',
    seoImpact: 'medium',
    errorMessage: 'video is recommended for enhanced display',
    fix: 'Add "video": {"@type": "VideoObject", "name": "...", "description": "...", "thumbnailUrl": "..."}',
    documentation: 'https://developers.google.com/search/docs/appearance/structured-data/recipe',
  },
];
