/**
 * VideoObject Schema Validation Rules
 * https://schema.org/VideoObject
 * https://developers.google.com/search/docs/appearance/structured-data/video
 */

import type { ValidationRule} from '../types';

export const videoObjectRules: ValidationRule[] = [
  {
    property: '@context',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: '@context must be "https://schema.org"',
    fix: 'Set "@context": "https://schema.org"',
    documentation: 'https://schema.org/VideoObject',
  },
  {
    property: '@type',
    required: true,
    type: 'string',
    seoImpact: 'high',
    errorMessage: '@type must be "VideoObject"',
    fix: 'Set "@type": "VideoObject"',
    documentation: 'https://schema.org/VideoObject',
  },
  {
    property: 'name',
    required: true,
    type: 'string',
    minLength: 5,
    seoImpact: 'high',
    errorMessage: 'name (video title) is required',
    fix: 'Add "name": "Video Title"',
    documentation: 'https://schema.org/name',
  },
  {
    property: 'description',
    required: true,
    type: 'string',
    minLength: 50,
    seoImpact: 'high',
    errorMessage: 'description is required',
    fix: 'Add "description": "Video description"',
    documentation: 'https://schema.org/description',
  },
  {
    property: 'thumbnailUrl',
    required: true,
    type: ['string', 'array'],
    googleRequirement: {
      minWidth: 60,
      minHeight: 30,
    },
    seoImpact: 'high',
    errorMessage: 'thumbnailUrl is required (must be at least 60x30 pixels, recommended: 1200x675)',
    fix: 'Add "thumbnailUrl": "https://example.com/thumbnail.jpg"',
    documentation: 'https://developers.google.com/search/docs/appearance/structured-data/video',
  },
  {
    property: 'uploadDate',
    required: true,
    type: 'string',
    format: 'iso8601-date',
    seoImpact: 'high',
    errorMessage: 'uploadDate is required in ISO 8601 format',
    fix: 'Add "uploadDate": "2024-01-15"',
    documentation: 'https://schema.org/uploadDate',
  },
  {
    property: 'duration',
    required: false,
    type: 'string',
    format: 'iso8601-duration',
    seoImpact: 'medium',
    errorMessage: 'duration should be in ISO 8601 duration format',
    fix: 'Add "duration": "PT10M30S" (for 10 minutes 30 seconds)',
    documentation: 'https://schema.org/duration',
  },
  {
    property: 'contentUrl',
    required: false,
    type: 'string',
    seoImpact: 'medium',
    errorMessage: 'contentUrl is recommended (direct link to video file)',
    fix: 'Add "contentUrl": "https://example.com/video.mp4"',
    documentation: 'https://schema.org/contentUrl',
  },
  {
    property: 'embedUrl',
    required: false,
    type: 'string',
    seoImpact: 'medium',
    errorMessage: 'embedUrl is recommended (URL for video player)',
    fix: 'Add "embedUrl": "https://example.com/embed/video123"',
    documentation: 'https://schema.org/embedUrl',
  },
  {
    property: 'expires',
    required: false,
    type: 'string',
    format: 'iso8601-datetime',
    seoImpact: 'low',
    errorMessage: 'expires date indicates when video will no longer be available',
    fix: 'Add "expires": "2024-12-31T23:59:59Z"',
    documentation: 'https://schema.org/expires',
  },
  {
    property: 'interactionStatistic',
    required: false,
    type: 'object',
    seoImpact: 'low',
    errorMessage: 'interactionStatistic (view count) is optional but helpful',
    fix: 'Add "interactionStatistic": {"@type": "InteractionCounter", "interactionType": {"@type": "WatchAction"}, "userInteractionCount": 1000}',
    documentation: 'https://schema.org/interactionStatistic',
  },
  {
    property: 'regionsAllowed',
    required: false,
    type: ['string', 'array'],
    seoImpact: 'low',
    errorMessage: 'regionsAllowed indicates geographic restrictions',
    fix: 'Add "regionsAllowed": "US,CA" or "regionsAllowed": ["US", "CA"]',
    documentation: 'https://schema.org/regionsAllowed',
  },
  {
    property: 'hasPart',
    required: false,
    type: ['object', 'array'],
    seoImpact: 'medium',
    errorMessage: 'hasPart enables key moments/seek functionality',
    fix: 'Add "hasPart": [{"@type": "Clip", "name": "Intro", "startOffset": 0, "endOffset": 30, "url": "..."}]',
    documentation: 'https://developers.google.com/search/docs/appearance/structured-data/video',
  },
  {
    property: 'publication',
    required: false,
    type: ['object', 'array'],
    seoImpact: 'low',
    errorMessage: 'publication indicates where video appears',
    fix: 'Add "publication": {"@type": "BroadcastEvent", "isLiveBroadcast": true, "startDate": "..."}',
    documentation: 'https://schema.org/publication',
  },
];
